### ISSUE TITLE
sparql enhancement - service keyword

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#461]
Would be nice to be able to query external sparql endpoints in a federated query.  Not sure that this can be done in the plugin, but this is a request to investigate and if possible enable queries with the `service` keyword.

Currently, queries with `service` result in a class not found exception:
`2020-08-04 17:04:53.608 [AWT-EventQueue-0] ERROR ProtegeApplication    Uncaught Exception in thread 'AWT-EventQueue-0'
java.lang.NoClassDefFoundError: org/apache/commons/httpclient/HttpMethod
	at org.openrdf.repository.sparql.SPARQLRepository.createHTTPClient(SPARQLRepository.java:92) ~[sparql-query-plugin-2.1.2.jar:na]`

**Comment by NCIEVS** [comment]
Better to update jars rather than add "service" functionality to existing.  Probably eliminates some of the other sparql performance issues.

**Comment by NCIEVS** [comment]
works in sparql plugin 2.1.8 using sesame 2.7.12 jars.  involved adding missing jars.  can be queued for QA in next build.

**Comment by bdionne** [comment]
updated to sparql-query-plugin-2.1.9 - there was one more missing jar

**Comment by singhik** [comment]
@NCIEVS : Hi, 

1. I ran a Sample SPARQL Query with a 'Service' link to an external Remote Endpoint, SPARQL Editor did  **not** throw any Exception or Error indicating it is able to make remote connections to external endpoints . 

2. Invoking external endpoints may have restrictions on  communication 'protocol' used & intranet n/w restrictions , the one i tested was over http, if you have specific 'Service' endpoints or Sparql queries that you want me to Regression through , please share them , else this ticket can be closed with below referenced screeen print. 

Please advice : 

![image](https://user-images.githubusercontent.com/36314371/118042488-241c9b00-b342-11eb-9258-af21cd1e8a7c.png)

![image](https://user-images.githubusercontent.com/36314371/118042626-4dd5c200-b342-11eb-9a72-9be5dba4e517.png)

![image](https://user-images.githubusercontent.com/36314371/118042712-6940cd00-b342-11eb-9849-01bfaeb20683.png)

**Comment by fragosog** [comment]
Hi @singhik , that looks like a good test against a public server.  Hopefully the test query doesn't hit those resources heavily :-)  There won't be a resultset because the 'join' is looking for data in the ncit that doesn't exist.  But i can rewrite that query so the entire dataset is retrieved from the remote endpoint.  Send me your query offline and i'll look at it.
